---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Include test vars
      ansible.builtin.include_vars: vars.yml
    - name: Update apt cache
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: bouquet_stack
