---
_debug: true # noqa var-naming[no-role-prefix]
docker_service_manage: true # noqa var-naming[no-role-prefix]

bouquet_stack_map:
  bouquet_test:
    services:
      app:
        environment:
          MYSQL_DATABASE: app
          MYSQL_HOST: db
          MYSQL_PASSWORD: app
          MYSQL_USER: app
        image: nginx
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./data:/app/data
          - ./config:/app/config

      db:
        environment:
          - MARIADB_DATABASE=app
          - MARIADB_USER=app
          - MARIADB_PASSWORD=app
          - MARIADB_ROOT_PASSWORD=s3cr3t
        image: mariadb
        volumes:
          - ./data:/var/lib/mysql
