#!/usr/bin/env bash
# mise description="Install ansible requirements"
# mise depends=["pip:install"]

if [ -f requirements.yml ]
then
    ansible-galaxy install \
        --force \
        --role-file requirements.yml
fi
